use employee_db;
insert into department (name) values 
("Upper Management"),
("HR - Human Resources"),
("I.T Department"),
("Sales Department"),
("Accounting Department"),
("Payroll Department"),
("Logistics Department"),
("Customer Service Department"),
("Recruiting Department");

insert into role (title, salary, department_id) values
("HR Cordinator", 65000, 1),
("Payroll Coordinator", 60000, 1),
("I.T Manager", 73500, 2),
("e-commerce manager", 56000, 2),
("Data Entry", 30000, 2),
("SQL Database Admi  n", 68475, 2),
("Prodcut Specialist", 66000, 2),
("Jr. Dev", 50000, 2),
("Magento Specialist", 100000, 2),
("Full Stack Developer", 90000, 2),
("Scrum Master", 86000, 2),
("Warhouse Operations Managment", 74012, 3),
("President of Sales", 115000, 3),
("Branch Manager of Sales", 63000, 3),
("Fulfillment Director", 70000, 3),
("Project Manager", 115000, 3),
("Director of Sales Reps", 95000, 3),
("Accounts Receivable Analyst", 60000, 4),
("Accounts Payable Analyst", 60000, 4),
("Project Accountant", 80000, 4),
("Senior Accountant", 90000, 4),
("Work Force Coordinator", 50000, 5),
("Administrative Assistant", 52000, 6),
("Recruitment Specialist", 60000, 7),
("Payroll Administrator", 75000, 9);

insert into employee (first_name, last_name, role_id, manager_id) values
("Matt", "Hiatt", 2, null),
("Devon","Gram", 2, null),
("Kristy", "Bonachini", 7, null),
("Greg","Oostman", 2, 4),
("Jordan","Luxinlurburg", 1, 2),
("Jerrod","Davenport", 2, null),
("Makayla","McHolms", 6, null),
("Sarah","Koliniski", 5, null),
("Amy","Rudenburg", 8, null),
("Tim","Borre", 7, 1),
("Chris","Vishimi", 1, 3),
("Maddi","Bubz", 1, 4),
("Sage","Kaveliac", 5, 2),
("Kevin","Mosser", 1, null),
("Sarah","Test", 7,null),
("Amy","Test", 8,null),
("Tim","Test", 17,1),
("Chris","Test", null),
("Maddi","Test", 7),
("Sage","Test", 4, 9),
("Kevin","Test", 9, null);